# Generated by Django 5.2.4 on 2025-07-20 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=200)),
                ('nombre_equipes', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name="Nombre d'équipes")),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
            ],
        ),
    ]
