# Generated by Django 5.2.4 on 2025-07-20 16:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='date_tournoi',
            field=models.DateField(default=datetime.date.today, verbose_name='Date du tournoi'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='declarant',
            field=models.CharField(default='inconnu', max_length=200),
        ),
        migrations.AddField(
            model_name='declaration',
            name='email_club',
            field=models.EmailField(default='inconnu@exemple.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Email non valide')]),
        ),
        migrations.AddField(
            model_name='declaration',
            name='remarques',
            field=models.TextField(blank=True),
        ),
    ]
