# Generated by Django 5.2.4 on 2025-07-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0003_declaration_categorie_age_declaration_sexe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='declaration',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saisie_equipes.club', verbose_name='Club affilié'),
        ),
    ]
