# Generated by Django 5.2.4 on 2025-07-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0004_club_alter_declaration_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='zone',
            field=models.CharField(blank=True, choices=[('N', 'Zone Nord'), ('S', 'Zone Sud'), ('', 'Pas de zone')], max_length=1, null=True, verbose_name='Zone géographique (si applicable)'),
        ),
    ]
