# Generated by Django 5.2.4 on 2025-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0005_alter_declaration_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='zone',
            field=models.CharField(blank=True, choices=[('N', 'Zone Nord'), ('S', 'Zone Sud'), ('', 'Pas de zone')], default='', max_length=1, verbose_name='Zone géographique si applicable'),
        ),
    ]
