# Generated by Django 5.2.4 on 2025-07-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0006_alter_declaration_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-date_declaration'], 'verbose_name': 'Déclaration', 'verbose_name_plural': 'Déclarations'},
        ),
    ]
