# Generated by Django 5.0.7 on 2026-01-07 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0007_alter_declaration_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declarant',
            field=models.CharField(default='Vos Nom et Prénom', max_length=200, verbose_name='Déclarant'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='email_club',
            field=models.EmailField(default='votre_email@exemple.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Email non valide')]),
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date à laquelle le tournoi aura lieu', verbose_name='Date du tournoi')),
                ('categorie_age', models.CharField(choices=[('M11', 'Moins de 11 ans'), ('M13', 'Moins de 13 ans'), ('M15', 'Moins de 15 ans'), ('M18', 'Moins de 18 ans')], help_text='Ex: M11, M13, M15, M18', max_length=3, verbose_name="Catégorie d'âge")),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Masculin ou Féminin', max_length=1, verbose_name='Sexe')),
                ('zone', models.CharField(blank=True, choices=[('N', 'Zone Nord'), ('S', 'Zone Sud'), ('', 'Pas de zone')], help_text='Nord, Sud, ou vide si pas de zone', max_length=1, verbose_name='Zone géographique')),
                ('lieu', models.CharField(blank=True, help_text='Nom du gymnase (défini après validation candidature)', max_length=200, verbose_name='Lieu / Gymnase')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='PLANIFIE', help_text='État actuel du tournoi', max_length=20, verbose_name='Statut')),
                ('est_publie', models.BooleanField(default=True, help_text='Si False, seul le staff voit le tournoi', verbose_name='Publié')),
                ('remarques', models.TextField(blank=True, help_text='Notes du staff (non visibles publiquement)', verbose_name='Remarques internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('club_organisateur', models.ForeignKey(blank=True, help_text="Club responsable de l'organisation (défini après validation candidature)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournois_organises', to='saisie_equipes.club', verbose_name='Club organisateur')),
                ('created_by', models.ForeignKey(blank=True, help_text='Membre du staff qui a créé le tournoi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournois_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Tournoi',
                'verbose_name_plural': 'Tournois',
                'ordering': ['date', 'categorie_age', 'sexe'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declarant', models.CharField(help_text='Nom et prénom de la personne qui dépose la candidature', max_length=200, verbose_name='Personne de contact')),
                ('email_contact', models.EmailField(help_text='Email pour les notifications', max_length=254, validators=[django.core.validators.EmailValidator(message='Email non valide')], verbose_name='Email de contact')),
                ('telephone_contact', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel)', max_length=20, verbose_name='Téléphone')),
                ('lieu', models.CharField(help_text="Nom du gymnase où le club propose d'organiser", max_length=200, verbose_name='Lieu proposé')),
                ('remarques', models.TextField(blank=True, help_text='Commentaires du club sur sa candidature', verbose_name='Remarques / Motivations')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('RETIREE', 'Retirée')], default='EN_ATTENTE', help_text='État de traitement de la candidature', max_length=20, verbose_name='Statut')),
                ('raison_refus', models.TextField(blank=True, help_text='Si refusée, explication donnée au club', verbose_name='Raison du refus')),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Quand la candidature a été validée/refusée', null=True, verbose_name='Date de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='saisie_equipes.club', verbose_name='Club candidat')),
                ('traite_par', models.ForeignKey(blank=True, help_text='Membre du staff qui a validé/refusé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='saisie_equipes.tournoi', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='tournoi',
            field=models.ForeignKey(blank=True, help_text="Tournoi pour lequel l'équipe est déclarée", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='saisie_equipes.tournoi', verbose_name='Tournoi'),
        ),
        migrations.AddIndex(
            model_name='tournoi',
            index=models.Index(fields=['date'], name='saisie_equi_date_0adb55_idx'),
        ),
        migrations.AddIndex(
            model_name='tournoi',
            index=models.Index(fields=['statut'], name='saisie_equi_statut_7cab6f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournoi',
            index=models.Index(fields=['date', 'statut'], name='saisie_equi_date_fd4730_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournoi',
            unique_together={('date', 'categorie_age', 'sexe', 'zone')},
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut'], name='saisie_equi_statut_471836_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['tournoi', 'statut'], name='saisie_equi_tournoi_7c62ef_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['club', 'statut'], name='saisie_equi_club_id_935170_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('tournoi', 'club')},
        ),
    ]
