# Generated by Django 5.0.7 on 2026-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0008_alter_declaration_declarant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='titre',
            field=models.CharField(blank=True, help_text="Ex: 'Journée 2', 'Tournoi de Noël'", max_length=100, verbose_name='Titre du tournoi'),
        ),
    ]
