# Generated by Django 5.0.7 on 2026-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0009_tournoi_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='titre',
            field=models.CharField(blank=True, help_text="Ex: 'Journée 2', 'FINALITÉ'", max_length=100, verbose_name='Titre du tournoi'),
        ),
    ]
