# Generated by Django 5.0.7 on 2026-02-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0010_alter_tournoi_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='noms_equipes',
            field=models.JSONField(blank=True, default=list, verbose_name='Noms des équipes'),
        ),
    ]
