# Generated by Django 5.0.7 on 2026-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0011_declaration_noms_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='noms_equipes',
            field=models.JSONField(blank=True, default=list, help_text="Liste des noms d'équipes (ex: ['TGV A', 'TGV B'])", verbose_name='Noms des équipes'),
        ),
    ]
