# Generated by Django 5.0.7 on 2026-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0012_alter_declaration_noms_equipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='poules_equipes',
            field=models.JSONField(blank=True, default=list, help_text="Liste des poules assignées à chaque équipe (ex: ['HAUTE', 'BASSE', ''])", verbose_name='Poules des équipes'),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='poules_disponibles',
            field=models.JSONField(blank=True, default=list, help_text="Liste des poules disponibles pour ce tournoi (ex: ['HAUTE', 'BASSE'] ou ['UNIQUE'])", verbose_name='Poules disponibles'),
        ),
    ]
