# Generated by Django 5.0.7 on 2026-02-24 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0013_declaration_poules_equipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declarant',
            field=models.CharField(max_length=200, verbose_name='Déclarant'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='email_club',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Email non valide')], verbose_name='Email du club'),
        ),
    ]
