# Generated by Django 5.0.7 on 2026-03-05 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0014_alter_declaration_declarant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='categorie_age',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='date_tournoi',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='zone',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='poules_equipes',
            field=models.JSONField(blank=True, default=list, help_text='Liste des poules assignées à chaque équipe', verbose_name='Poules des équipes'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='tournoi',
            field=models.ForeignKey(help_text="Tournoi pour lequel l'équipe est déclarée", on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='saisie_equipes.tournoi', verbose_name='Tournoi'),
        ),
    ]
