# Generated by Django 5.0.7 on 2026-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie_equipes', '0016_alter_tournoi_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('X', 'Féminin et Masculin')], default='X', help_text='Masculin ou Féminin ou les deux catégories', max_length=1, verbose_name='Sexe'),
        ),
    ]
